import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "@yoophi/ui-base/components/button";
import { Input } from "@yoophi/ui-base/components/input";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@yoophi/ui-base/components/card";
import { ScrollArea } from "@yoophi/ui-base/components/scroll-area";
import { Badge } from "@yoophi/ui-base/components/badge";
import { Label } from "@yoophi/ui-base/components/label";
import { Textarea } from "@yoophi/ui-base/components/textarea";
import { Separator } from "@yoophi/ui-base/components/separator";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@yoophi/ui-base/components/select";
import { Combobox, ComboboxInput, ComboboxContent, ComboboxList, ComboboxItem, ComboboxEmpty } from "@yoophi/ui-base/components/combobox";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from "@yoophi/ui-base/components/dialog";
import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel } from "@yoophi/ui-base/components/alert-dialog";
import { ContextMenu, ContextMenuTrigger, ContextMenuContent, ContextMenuItem } from "@yoophi/ui-base/components/context-menu";
const meta = { title: "Base UI/컴포넌트", component: Button, args: { children: "버튼" } } satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export const ButtonPlayground: Story = {};
export const Buttons: Story = { render: () => <div className="flex flex-wrap gap-3">{(["default", "secondary", "outline", "ghost", "destructive", "link"] as const).map((variant) => <Button key={variant} variant={variant}>{variant}</Button>)}<Button disabled>Disabled</Button></div> };
export const Inputs: Story = { render: () => <div className="max-w-sm space-y-3"><Input aria-label="폴더 이름" placeholder="폴더 이름" /><Input aria-label="읽기 전용 값" value="읽기 전용" readOnly /><Input aria-label="비활성 입력" placeholder="Disabled" disabled /><Input aria-label="잘못된 값" aria-invalid defaultValue="invalid" /></div> };
export const Cards: Story = { render: () => <Card className="max-w-sm"><CardHeader><CardTitle>공통 탐색 UI</CardTitle><CardDescription>소비 앱이 데이터와 이벤트를 제공합니다.</CardDescription></CardHeader><CardContent>카드 본문</CardContent><CardFooter><Button>열기</Button></CardFooter></Card> };
export const Scrolling: Story = { render: () => <ScrollArea className="h-48 w-72 rounded border"><div className="p-4">{Array.from({ length: 30 }, (_, i) => <p key={i} className="py-2">폴더 {i + 1}</p>)}</div></ScrollArea> };
export const FormPrimitives: Story = { render: () => <div className="max-w-sm space-y-4"><Badge>기본</Badge> <Badge variant="outline">Outline</Badge><Separator /><Label htmlFor="story-note">설명</Label><Textarea id="story-note" placeholder="설명을 입력하세요" /></div> };
export const Selection: Story = { render: () => <Select defaultValue="name"><SelectTrigger aria-label="정렬"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="name">이름</SelectItem><SelectItem value="date">날짜</SelectItem><SelectItem value="size" disabled>크기 (비활성)</SelectItem></SelectContent></Select> };
export const SearchableSelection: Story = { render: () => <div className="max-w-sm"><Combobox items={["Movies", "Documents", "Archive"]}><ComboboxInput aria-label="폴더 검색" placeholder="폴더 검색" /><ComboboxContent><ComboboxEmpty>결과 없음</ComboboxEmpty><ComboboxList>{(item: string) => <ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div> };
export const Modal: Story = { render: () => <Dialog><DialogTrigger render={<Button />}>설정 열기</DialogTrigger><DialogContent><DialogHeader><DialogTitle>설정</DialogTitle><DialogDescription>공통 Dialog의 포커스와 닫기 동작을 확인합니다.</DialogDescription></DialogHeader><Input aria-label="폴더 이름" placeholder="폴더 이름" /><DialogFooter><DialogClose render={<Button />}>완료</DialogClose></DialogFooter></DialogContent></Dialog> };
export const Confirmation: Story = { render: () => <AlertDialog><AlertDialogTrigger render={<Button variant="destructive" />}>삭제 확인</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>항목을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>예제이므로 실제 데이터는 삭제하지 않습니다.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>취소</AlertDialogCancel><AlertDialogCancel variant="destructive">삭제</AlertDialogCancel></AlertDialogFooter></AlertDialogContent></AlertDialog> };
export const ContextActions: Story = { render: () => <ContextMenu><ContextMenuTrigger className="block rounded border border-dashed p-12">여기에서 마우스 오른쪽 버튼을 누르세요.</ContextMenuTrigger><ContextMenuContent><ContextMenuItem>열기</ContextMenuItem><ContextMenuItem>이름 복사</ContextMenuItem><ContextMenuItem disabled>삭제 (비활성)</ContextMenuItem></ContextMenuContent></ContextMenu> };
