import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "@yoophi/ui-radix/components/button";
import { Input } from "@yoophi/ui-radix/components/input";
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@yoophi/ui-radix/components/card";
import { ScrollArea } from "@yoophi/ui-radix/components/scroll-area";
import { Skeleton } from "@yoophi/ui-radix/components/skeleton";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@yoophi/ui-radix/components/empty";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@yoophi/ui-radix/components/table";
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from "@yoophi/ui-radix/components/resizable";
const meta = { title: "Radix UI/컴포넌트", component: Button, args: { children: "버튼" } } satisfies Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export const ButtonPlayground: Story = {};
export const Buttons: Story = { render: () => <div className="flex flex-wrap gap-3">{(["default", "secondary", "outline", "ghost", "destructive", "link"] as const).map((variant) => <Button key={variant} variant={variant}>{variant}</Button>)}<Button disabled>Disabled</Button></div> };
export const Inputs: Story = { render: () => <div className="max-w-sm space-y-3"><Input aria-label="폴더 이름" placeholder="폴더 이름" /><Input aria-label="읽기 전용 값" value="읽기 전용" readOnly /><Input aria-label="비활성 입력" placeholder="Disabled" disabled /><Input aria-label="잘못된 값" aria-invalid defaultValue="invalid" /></div> };
export const Cards: Story = { render: () => <Card className="max-w-sm"><CardHeader><CardTitle>공통 탐색 UI</CardTitle><CardDescription>소비 앱이 데이터와 이벤트를 제공합니다.</CardDescription></CardHeader><CardContent>카드 본문</CardContent><CardFooter><Button>열기</Button></CardFooter></Card> };
export const Scrolling: Story = { render: () => <ScrollArea className="h-48 w-72 rounded border"><div className="p-4">{Array.from({ length: 30 }, (_, i) => <p key={i} className="py-2">폴더 {i + 1}</p>)}</div></ScrollArea> };
export const Loading: Story = { render: () => <div className="max-w-sm space-y-3"><Skeleton className="h-6 w-2/3" /><Skeleton className="h-4 w-full" /><Skeleton className="h-4 w-4/5" /></div> };
export const EmptyState: Story = { render: () => <Empty><EmptyHeader><EmptyTitle>항목 없음</EmptyTitle><EmptyDescription>폴더를 선택해 탐색을 시작하세요.</EmptyDescription></EmptyHeader></Empty> };
export const DataTable: Story = { render: () => <Table><TableHeader><TableRow><TableHead>이름</TableHead><TableHead>종류</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Movies</TableCell><TableCell>폴더</TableCell></TableRow><TableRow><TableCell>README.md</TableCell><TableCell>파일</TableCell></TableRow></TableBody></Table> };
export const Resizable: Story = { render: () => <ResizablePanelGroup orientation="horizontal" className="min-h-64 rounded border"><ResizablePanel defaultSize="30%" minSize="15%"><div className="p-6">폴더 트리</div></ResizablePanel><ResizableHandle withHandle /><ResizablePanel><div className="p-6">파일 목록 — 경계선을 드래그하거나 키보드로 조절하세요.</div></ResizablePanel></ResizablePanelGroup> };
